#############################################################################
# Makefile for building: libqm-vamp-plugins.so.1.0.0
# Generated by qmake (1.07a) (Qt 3.3.4) on: Wed Apr  5 17:23:42 2006
# Project:  qm-vamp-plugins.pro
# Template: lib
# Command: $(QMAKE) -o Makefile qm-vamp-plugins.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -fPIC  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -fPIC  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I../../sonic-visualiser/plugin/vamp-plugin-sdk -I../../qm-dsp/trunk -I. -Iplugins -I/usr/include/qt3 -Itmp_moc/
LINK     = g++
LFLAGS   = -shared -Wl,-soname,libqm-vamp-plugins.so.1
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = tmp_obj/

####### Files

HEADERS = plugins/BeatDetect.h \
		plugins/ChromagramPlugin.h \
		plugins/TonalChangeDetect.h
SOURCES = plugins/BeatDetect.cpp \
		plugins/ChromagramPlugin.cpp \
		plugins/TonalChangeDetect.cpp
OBJECTS = tmp_obj/BeatDetect.o \
		tmp_obj/ChromagramPlugin.o \
		tmp_obj/TonalChangeDetect.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = 
OBJMOC = 
DIST	   = qm-vamp-plugins.pro
QMAKE_TARGET = qm-vamp-plugins
DESTDIR  = 
TARGET   = libqm-vamp-plugins.so.1.0.0
TARGETA	= libqm-vamp-plugins.a
TARGETD	= libqm-vamp-plugins.so.1.0.0
TARGET0	= libqm-vamp-plugins.so
TARGET1	= libqm-vamp-plugins.so.1
TARGET2	= libqm-vamp-plugins.so.1.0

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile  $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: $(TARGETA)

$(TARGETA):  $(UICDECLS) $(OBJECTS) $(OBJMOC) $(OBJCOMP)
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS) $(OBJMOC)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: qm-vamp-plugins.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile qm-vamp-plugins.pro
qmake: 
	@$(QMAKE) -o Makefile qm-vamp-plugins.pro

dist: 
	@mkdir -p tmp_obj/qm-vamp-plugins && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) tmp_obj/qm-vamp-plugins/ && ( cd `dirname tmp_obj/qm-vamp-plugins` && $(TAR) qm-vamp-plugins.tar qm-vamp-plugins && $(GZIP) qm-vamp-plugins.tar ) && $(MOVE) `dirname tmp_obj/qm-vamp-plugins`/qm-vamp-plugins.tar.gz . && $(DEL_FILE) -r tmp_obj/qm-vamp-plugins

mocclean:

uiclean:

yaccclean:
lexclean:
clean:
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)


FORCE:

####### Compile

tmp_obj/BeatDetect.o: plugins/BeatDetect.cpp plugins/BeatDetect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_obj/BeatDetect.o plugins/BeatDetect.cpp

tmp_obj/ChromagramPlugin.o: plugins/ChromagramPlugin.cpp plugins/ChromagramPlugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_obj/ChromagramPlugin.o plugins/ChromagramPlugin.cpp

tmp_obj/TonalChangeDetect.o: plugins/TonalChangeDetect.cpp plugins/TonalChangeDetect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_obj/TonalChangeDetect.o plugins/TonalChangeDetect.cpp

####### Install

install:  

uninstall:  

